{% set version = "0.12.1" %}

package:
  name: glue-vispy-viewers
  version: {{version}}

source:
  fn: glue-vispy-viewers-{{version}}.tar.gz
  url: https://pypi.io/packages/source/g/glue-vispy-viewers/glue-vispy-viewers-{{version}}.tar.gz
  sha256: 9ab0c6b28de90f9155ef4c37028dcc8af369274b91b7d6432fbe9ba99bb16f5a

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:

  build:
    - python
    - pip
    - setuptools >=30.3
    - setuptools_scm

  run:
    - python
    - numpy
    - pyopengl
    - glue-core >=0.15
    - qtpy
    - pyqt
    - astropy >=1.1
    - pillow
    - matplotlib

test:
  imports:
    - glue_vispy_viewers
    - glue_vispy_viewers.scatter
    - glue_vispy_viewers.volume

about:
  home: https://github.com/glue-viz/glue-vispy-viewers
  license: BSD 3-Clause
  summary: 3D viewers for Glue based on Vispy

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
