{% set version = "1.0.0" %}

package:
  name: glue-vispy-viewers
  version: {{ version }}

source:
  fn: glue-vispy-viewers-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/glue-vispy-viewers/glue-vispy-viewers-{{ version }}.tar.gz
  sha256: aea3a9792c374976fa766d8252297c0874948a29146b364a2f4b1ef0b43f4448

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:

  build:
    - python
    - pip
    - setuptools >=30.3
    - setuptools_scm

  run:
    - python
    - numpy
    - pyopengl
    - glue-core >=0.15
    - qtpy
    - pyqt
    - astropy >=1.1
    - pillow
    - matplotlib-base

test:
  imports:
    - glue_vispy_viewers
    - glue_vispy_viewers.scatter
    - glue_vispy_viewers.volume

about:
  home: https://github.com/glue-viz/glue-vispy-viewers
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 3D viewers for Glue based on Vispy

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
